drop table if exists usr_pairs;
drop table if exists user_role;
drop table if exists pairs;
drop table if exists usr;
drop table if exists kitty;

create table kitty
(
    id     int4 generated by default as identity,
    name   varchar(255) not null,
    rating float8       not null,
    photo  varchar(255) not null,
    primary key (id)
);

create table pairs
(
    id   int8 generated by default as identity,
    a_id int4 not null,
    b_id int4 not null,
    primary key (id)
);

create table user_role
(
    user_id int8 not null,
    roles   varchar(255)
);

create table usr
(
    id       int8 generated by default as identity,
    password varchar(255),
    username varchar(255),
    kitty_id int4,
    primary key (id)
);

create table usr_pairs
(
    user_id  int8 not null,
    pairs_id int8 not null
);

alter table if exists user_role
    add constraint user_role_c foreign key (user_id) references usr;

alter table if exists usr
    add constraint usr_c foreign key (kitty_id) references kitty;

alter table if exists usr_pairs
    add constraint usr_pairs_c foreign key (pairs_id) references pairs;

alter table if exists usr_pairs
    add constraint usr_pair_c_t foreign key (user_id) references usr;